global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: 'otel-collector'
  scrape_interval: 10s
  static_configs:
    - targets: 
      - 'otel-collector:8889'
      - 'otel-collector:8888'
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: telematicsservice
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - telematicsservice.worker:9464
        - livemapbff.webapi:9464
        - livemapbff.notificationshub:9464
        - telematicsservice.webapi:9464
  